### ISSUE TITLE
Only change the version, don't format

### ISSUE THREAD

**Issue by cwrau** [ekeih/heluxup#7]
Currently, when I run `heluxup .` it successfully updates my Helm charts, but also formats and document splits(?) my YAML files:

Before:
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: ingress
spec:
  releaseName: external-dns
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: external-dns
    version: 2.10.2
  values:
    sources:
      - service
      - ingress
      - crd
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        drop:
          - ALL
      runAsGroup: 1001
      runAsUser: 1001
```

After:
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: ingress
spec:
  releaseName: external-dns
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: external-dns
    version: 2.10.3
  values:
    sources:
    - service
    - ingress
    - crd
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1001
      runAsUser: 1001
```

Diff:
```diff
diff --git a/ingress/external-dns.yaml b/ingress/external-dns.yaml
index 53c5cde..ee1054b 100644
--- a/ingress/external-dns.yaml
+++ b/ingress/external-dns.yaml
@@ -1,3 +1,4 @@
+---
 apiVersion: helm.fluxcd.io/v1
 kind: HelmRelease
 metadata:
@@ -8,7 +9,7 @@ spec:
   chart:
     repository: https://kubernetes-charts.storage.googleapis.com/
     name: external-dns
-    version: 2.10.2
+    version: 2.10.3
   values:
     cloudflare:
       apiKey: SEEEEEEECREEEEEEEET
@@ -16,9 +17,9 @@ spec:
       proxied: false
     provider: cloudflare
     sources:
-      - service
-      - ingress
-      - crd
+    - service
+    - ingress
+    - crd
     rbac:
       create: true
     crd:
@@ -34,7 +35,7 @@ spec:
       privileged: false
       capabilities:
         drop:
-          - ALL
+        - ALL
       runAsGroup: 1001
       runAsUser: 1001
     resources:
```

Therefore I have to reformat the YAML files after each update and also remove the `---`.

It would be awesome if you could only change the version 🤗
